### PR TITLE
link to haskell-cafe mailman archives

### PR DESCRIPTION
**Pull request by jwaldmann**
Works for me now. 
Contains some ugly DOM tree walks. 
For https downloads, I am using Network.HTTP.Conduit (not Curl). 
I removed the cabal.config pinned versions since I could not get this to compile (ghc-7.8.4).

### CODE REVIEW

**Comment by chrisdone** [comment]
I'll get to this the next day or so, thanks.

**Comment by lwm** [comment]
@jwaldmann, thanks for working on this. Would you mind to rebase on master, resolve conflicts and reduce commits to only ones created by yourself? I'd be happy to review and move this one forward!

**Comment by jwaldmann** [comment]
I'll look into this.

**Comment by lwm** [comment]
Unfortunately, a bunch of changes have come in recently (See `CHANGELOG.md`) making the rebase and merge conflict resolution a possible nightmare (sorry!). Will close for now. Please come back with your changes and I'll be happy to review/merge.

**Comment by beerendlauwers** [comment]
@jwaldmann This PR has gained increased awareness due to https://github.com/haskellnews/haskellnews/issues/51. Do you happen to have the time to have a look at this again? If not, I'll poke around a bit.

**Comment by lwm** [comment]
Go go go go go go go go :+1:

**Comment by jwaldmann** [comment]
I will give this a try.

**Comment by jwaldmann** [comment]
I just made a pull request (#53)

**Pull request closed without merging**
